# Generated by Django 5.0.6 on 2024-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='media/')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
